# Generated by Django 3.2.9 on 2021-11-10 20:36

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        TrigramExtension(),
    ]
