# Generated by Django 3.2.9 on 2021-11-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("automatic_checks", "0001_install_trigram_extension"),
    ]

    operations = [
        migrations.CreateModel(
            name="Properties",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_modified", models.DateTimeField()),
                ("db_schema_version", models.IntegerField()),
                ("version", models.IntegerField()),
                ("dblp_version", models.DateField()),
                ("semantic_scholar_version", models.DateField()),
                ("aminer_mag_version", models.DateField()),
            ],
            options={
                "db_table": "properties",
            },
        ),
    ]
