# Generated by Django 3.2.9 on 2021-11-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automatic_checks", "0002_properties"),
    ]

    operations = [
        migrations.AlterField(
            model_name="properties",
            name="aminer_mag_version",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="properties",
            name="dblp_version",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="properties",
            name="semantic_scholar_version",
            field=models.DateField(null=True),
        ),
    ]
