# Generated by Django 3.2.9 on 2021-11-10 22:32

from datetime import datetime

from django.db import migrations


def populate_properties(apps, schema_editor):
    Properties = apps.get_model("automatic_checks", "Properties")
    Properties(
        last_modified = datetime.now(),
        db_schema_version = 11,
        version = 1,
    ).save()


class Migration(migrations.Migration):

    dependencies = [
        ("automatic_checks", "0003_auto_20211110_2232"),
    ]

    operations = [
        migrations.RunPython(populate_properties),
    ]
