version: "3.9"

services:
  gateway:
    build:
      context: ./services
      dockerfile: ./gateway/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./services/backend
      target: development
    env_file:
      - .env.example
    depends_on:
      - db

  db:
    build: ./services/db
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env.example

volumes:
  db_data:
