version: "3.9"

services:
  gateway:
    build:
      context: ./services
      dockerfile: ./gateway/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./services/backend
    depends_on:
      - db
    cap_add:
      - SYS_ADMIN

  db:
    build: ./services/db
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=aip
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  db_data: