version: '3'

volumes:
  db_data: {}

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - web

  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    volumes:
      - ./backend/src:/backend/src
    depends_on:
      - db

  db:
    build: ./docker/db
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=aip
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432