version: "3.9"

services:
  gateway:
    build:
      context: ./services
      dockerfile: ./gateway/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./services/backend
      target: production
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_DB=aip
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db

  db:
    build: ./services/db
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=aip
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  db_data:
  tunnel_data:
