version: "3.9"

services:
  gateway:
    build:
      context: ./services
      dockerfile: ./gateway/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./services/backend
      target: production
    env_file:
      - .env.production
    depends_on:
      - db

  db:
    build: ./services/db
    volumes:
      - /mnt/sdb/aip/docker/postgres:/var/lib/postgresql/data
    env_file:
      - .env.production