# Generated by Django 3.2.9 on 2021-11-10 21:28

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authors", "0002_auto_20211110_2128"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorPaperPairs",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("author_position", models.IntegerField(default=-1, null=True)),
            ],
            options={
                "db_table": "author_paper_pairs",
            },
        ),
        migrations.CreateModel(
            name="Cites",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "db_table": "cites",
            },
        ),
        migrations.CreateModel(
            name="PaperWordPairs",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cnt", models.IntegerField()),
            ],
            options={
                "db_table": "paper_word_pairs",
            },
        ),
        migrations.CreateModel(
            name="PublicationKeywordRelation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "db_table": "publication_keyword_relation",
            },
        ),
        migrations.CreateModel(
            name="Publications",
            fields=[
                ("id", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("title", models.CharField(blank=True, max_length=512)),
                ("abstract", models.TextField(blank=True, null=True)),
                ("venue", models.CharField(blank=True, max_length=64)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("volume", models.CharField(blank=True, max_length=32, null=True)),
                ("doi", models.CharField(blank=True, max_length=128, null=True)),
                ("n_citations", models.IntegerField(default=0)),
                ("semantic_scholar_id", models.CharField(blank=True, max_length=64, null=True, unique=True)),
            ],
            options={
                "db_table": "publications",
            },
        ),
        migrations.CreateModel(
            name="Words",
            fields=[
                ("word", models.CharField(max_length=32, primary_key=True, serialize=False)),
                ("frequency", models.IntegerField()),
            ],
            options={
                "db_table": "words",
            },
        ),
        migrations.AddIndex(
            model_name="words",
            index=models.Index(fields=["word"], name="words_word_8e8fba_idx"),
        ),
        migrations.AddIndex(
            model_name="words",
            index=models.Index(fields=["frequency"], name="words_frequen_b9735a_idx"),
        ),
        migrations.AddField(
            model_name="publications",
            name="authors",
            field=models.ManyToManyField(through="publications.AuthorPaperPairs", to="authors.Authors"),
        ),
        migrations.AddField(
            model_name="publications",
            name="citations",
            field=models.ManyToManyField(through="publications.Cites", to="publications.Publications"),
        ),
        migrations.AddField(
            model_name="publications",
            name="words",
            field=models.ManyToManyField(through="publications.PaperWordPairs", to="publications.Words"),
        ),
        migrations.AddField(
            model_name="publicationkeywordrelation",
            name="paper",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="publications.publications"),
        ),
        migrations.AddField(
            model_name="publicationkeywordrelation",
            name="word",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="publications.words"),
        ),
        migrations.AddField(
            model_name="paperwordpairs",
            name="paper",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="publications.publications"),
        ),
        migrations.AddField(
            model_name="paperwordpairs",
            name="word",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="publications.words"),
        ),
        migrations.AddField(
            model_name="cites",
            name="cited_paper",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cited_by", to="publications.publications"),
        ),
        migrations.AddField(
            model_name="cites",
            name="paper",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cites", to="publications.publications"),
        ),
        migrations.AddField(
            model_name="authorpaperpairs",
            name="author",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="authors.authors"),
        ),
        migrations.AddField(
            model_name="authorpaperpairs",
            name="paper",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="publications.publications"),
        ),
        migrations.AddIndex(
            model_name="publications",
            index=models.Index(fields=["n_citations"], name="publication_n_citat_067a30_idx"),
        ),
        migrations.AddIndex(
            model_name="publications",
            index=django.contrib.postgres.indexes.HashIndex(fields=["doi"], name="publication_doi_e22beb_hash"),
        ),
        migrations.AddIndex(
            model_name="publications",
            index=django.contrib.postgres.indexes.HashIndex(fields=["semantic_scholar_id"], name="publication_semanti_2b8f44_hash"),
        ),
        migrations.AddIndex(
            model_name="publications",
            index=django.contrib.postgres.indexes.HashIndex(fields=["title"], name="publication_title_71a17f_hash"),
        ),
        migrations.AddIndex(
            model_name="publications",
            index=django.contrib.postgres.indexes.HashIndex(fields=["venue"], name="publication_venue_6c6b3f_hash"),
        ),
        migrations.AddIndex(
            model_name="publications",
            index=django.contrib.postgres.indexes.HashIndex(fields=["volume"], name="publication_volume_496577_hash"),
        ),
        migrations.AddIndex(
            model_name="publications",
            index=models.Index(fields=["year"], name="publication_year_b3d1c4_idx"),
        ),
        migrations.AddIndex(
            model_name="publicationkeywordrelation",
            index=models.Index(fields=["paper"], name="publication_paper_i_c3ac5b_idx"),
        ),
        migrations.AddIndex(
            model_name="publicationkeywordrelation",
            index=models.Index(fields=["word"], name="publication_word_id_101d99_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="publicationkeywordrelation",
            unique_together={("paper", "word")},
        ),
        migrations.AddIndex(
            model_name="paperwordpairs",
            index=models.Index(fields=["paper"], name="paper_word__paper_i_8d9edf_idx"),
        ),
        migrations.AddIndex(
            model_name="paperwordpairs",
            index=models.Index(fields=["word"], name="paper_word__word_id_66e90f_idx"),
        ),
        migrations.AddIndex(
            model_name="paperwordpairs",
            index=models.Index(fields=["cnt"], name="paper_word__cnt_53fe1b_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="paperwordpairs",
            unique_together={("paper", "word")},
        ),
        migrations.AlterUniqueTogether(
            name="cites",
            unique_together={("paper", "cited_paper")},
        ),
        migrations.AlterUniqueTogether(
            name="authorpaperpairs",
            unique_together={("author", "paper")},
        ),
    ]
