# Generated by Django 3.2.5 on 2021-11-10 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="Authors",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=1024)),
                ("orcid", models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator("^\\d{4}-\\d{4}-\\d{4}-(\\d{3}X|\\d{4})$", message="ORCID must be a 16-digit identifier, formatted like xxxx-xxxx-xxxx-xxxx.")])),
                ("first_publication_year", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "authors",
            },
        ),
    ]
