# Generated by Django 3.2.9 on 2021-11-10 21:28

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="authors",
            index=django.contrib.postgres.indexes.HashIndex(fields=["name"], name="ind_author_name"),
        ),
        migrations.AddIndex(
            model_name="authors",
            index=django.contrib.postgres.indexes.HashIndex(fields=["orcid"], name="ind_author_orcid"),
        ),
        migrations.AddIndex(
            model_name="authors",
            index=models.Index(fields=["first_publication_year"], name="ind_first_publication"),
        ),
    ]
