name: Frontend

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'
    - name: Install packages
      run: yarn install --frozen-lockfile --immutable
      working-directory: services/frontend
    - name: Run tests
      run: yarn test
      working-directory: services/frontend